# Generated by Django 5.0.6 on 2024-06-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_naissance_alter_user_ntel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ntel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Num Tel'),
        ),
    ]
