# Generated by Django 5.0.6 on 2024-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_ntel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ntel',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Num Tel'),
        ),
    ]
