# Generated by Django 5.0.6 on 2024-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_ntel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update_profile',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update Profile'),
        ),
    ]
