# Generated by Django 5.0.6 on 2024-06-22 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomcategorie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomc', models.CharField(max_length=30)),
                ('Descriptionc', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course/')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Id_c', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backendApi.course')),
                ('Id_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomsouscategorie', models.CharField(max_length=30)),
                ('Descriptionsc', models.CharField(max_length=20, null=True)),
                ('Id_c', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backendApi.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Id_sc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backendApi.souscategorie'),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datesub', models.DateField()),
                ('typeS', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('Id_c', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backendApi.categorie')),
                ('Id_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
