# Generated by Django 5.0.6 on 2024-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
