# Generated by Django 5.0.6 on 2024-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0002_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscategorie',
            name='Descriptionsc',
        ),
        migrations.AddField(
            model_name='categorie',
            name='Descriptionc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
