# Generated by Django 5.0.6 on 2024-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0003_remove_souscategorie_descriptionsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
