# Generated by Django 5.0.6 on 2024-06-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0003_remove_souscategorie_descriptionsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Nomc',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
