# Generated by Django 5.0.6 on 2024-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0004_categorie_link_alter_course_nomc_alter_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
