# Generated by Django 5.0.6 on 2024-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0005_alter_favorite_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='Datesub',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='typeS',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=50),
        ),
    ]
