# Generated by Django 5.0.6 on 2024-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0005_alter_categorie_descriptionc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Nomc',
            field=models.CharField(max_length=100),
        ),
    ]
