# Generated by Django 5.0.6 on 2024-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0006_alter_course_nomc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
