# Generated by Django 5.0.6 on 2024-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0007_alter_favorite_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='DateDebSession',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='Datesub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
