# Generated by Django 5.0.6 on 2024-07-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0008_subscribe_datedebsession_subscribe_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Descriptionc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='Id_sc',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='backendApi.souscategorie'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Nomc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='prix',
            field=models.FloatField(blank=True),
        ),
    ]
