# Generated by Django 5.0.6 on 2024-07-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0006_subscribe_active_alter_subscribe_datesub_and_more'),
        ('backendApi', '0009_alter_course_descriptionc_alter_course_id_sc_and_more'),
    ]

    operations = [
    ]
