# Generated by Django 5.0.6 on 2024-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0010_merge_20240710_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Nomc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='Datesub',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='typeS',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=50),
        ),
    ]
